version: '3'

networks:
  skynet:
    driver: bridge

### flask worker (python) #####################################################
services:
  flask:
    build: ./python
    container_name: flask
    ports:
      - "8080:8080"
    volumes:
      - ./python:/usr/src/app
    command: python /usr/src/app/main.py
    networks:
      - skynet
### mongo #####################################################
  mongo:
    build: ./mongo
    ports:
      - "27017:27017"
    # volumes:
    #  - ./mongo:/data/db
    #  - ./mongo/data/db:/data/configdb
    networks:
      - skynet


